/* Generated by CCAN configurator */
#ifndef CCAN_CONFIG_H
#define CCAN_CONFIG_H
#ifndef _GNU_SOURCE
#define _GNU_SOURCE /* Always use GNU extensions. */
#endif
#define CCAN_COMPILER "cl"
#define CCAN_CFLAGS "-nologo -Zi -W4 -wd4200 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS"
#define CCAN_OUTPUT_EXE_CFLAG "-Fe:"

#define HAVE_CCAN 1
#define HAVE_UNALIGNED_ACCESS 1
#define HAVE_TYPEOF 1
#define HAVE_BIG_ENDIAN 0
#define HAVE_BYTESWAP_H 0
#define HAVE_BSWAP_64 0
#define HAVE_LITTLE_ENDIAN 1
#endif /* CCAN_CONFIG_H */
