# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CheckCCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/DartConfiguration.tcl.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Internal/CheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Internal/CheckFlagCommonConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/ext/secp256k1-0.3.2/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/ext/secp256k1-0.3.2/cmake/CheckStringOptionValue.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/ext/secp256k1-0.3.2/cmake/CheckX86_64Assembly.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/ext/secp256k1-0.3.2/cmake/FindValgrind.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/ext/secp256k1-0.3.2/cmake/TryAppendCFlags.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/ext/secp256k1-0.3.2/src/CMakeLists.txt))

/Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/osx-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -S/Users/Shared/gnostr.org/gnostr/deps/gnostr-relay -B/Users/Shared/gnostr.org/gnostr/deps/gnostr-relay/osx-build
